<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '< Отзыв о сайте >' => '',
  'IP адрес' => '',
  'Автор' => '',
  'Ваш комментарий успешно добавлен. Он будет опубликован после проверки администратором.' => '',
  'Ваш отзыв' => '',
  'Ваше имя' => '',
  'Введите текст с картинки:' => '',
  'Владелец' => '',
  'Дата обновления' => '',
  'Дата создания' => '',
  'Ждет одобрения' => '',
  'Загрузить еще' => '',
  'Изменения успешно сохранены' => '',
  'Имя' => '',
  'Код проверки' => '',
  'Комментарии' => '',
  'Комментарий' => '',
  'Комментарий не найден' => '',
  'Модель' => '',
  'Оставить отзыв' => '',
  'Отзывы о магазинах' => '',
  'Отправить' => '',
  'Ошибка проверки статуса.' => '',
  'Подтвержден' => '',
  'Позволяет оставлять комментарии к продуктам, страницам.' => '',
  'Почта' => '',
  'Редактирование комментария' => '',
  'Спам' => '',
  'Статус' => '',
  'Статус успешно изменен' => '',
  'Электронная почта' => '',
);
