<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '© «Интернет магазин»' => '',
  'В список желаний' => '',
  'Валюта:' => '',
  'Все права защищены' => '',
  'Все права принадлежат компании "Rivori" <span>&#174;</span>' => '',
  'Вход' => '',
  'Выход' => '',
  'Гарантия' => '',
  'Доставка и оплата' => '',
  'Интернет-магазин Ривори' => '',
  'Интернет-магазин, в котором вы найдете все:' => '',
  'Как сделать заказ' => '',
  'Личный кабинет' => '',
  'Мои заказы' => '',
  'Наши магазины' => '',
  'Обратная связь' => '',
  'Оплата заказа #' => '',
  'Оплатить' => '',
  'Поиск' => '',
  'Поиск товаров' => '',
  'Помощь' => '',
  'Регистрация' => '',
  'Ривори' => '',
  'Сообщить о появлении' => '',
  'Список желаний ({c})' => '',
  'Сравнить' => '',
  'Страница не найдена.' => '',
  'Товары на сравнение ({c})' => '',
);
