<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'CSV' => '',
  'Автоматизация' => '',
  'Доступны следующие поля:' => '',
  'Импорт' => '',
  'Импорт продуктов' => '',
  'Импорт/экспорт товаров, категорий, свойств в формате CSV.' => '',
  'Колонки name, category, type, price - обязательны.' => '',
  'Модули' => '',
  'Начать импорт' => '',
  'Обновлено продуктов: ' => '',
  'Ошибка. Директория для бэкапов недоступна для записи.' => '',
  'Первой строкой файла должны быть указаны колонки для импорта.' => '',
  'Пример файла' => '',
  'Разделитель поля - точка с запятой(;).' => '',
  'Скачать' => '',
  'Создано продуктов: ' => '',
  'Строка' => '',
  'Укажите обязательную колонку {column}.' => '',
  'Файл должен иметь кодировку UTF-8 или CP1251.' => '',
  'Файл недоступен.' => '',
  'Экспорт' => '',
  'Экспорт продуктов' => '',
  'и еще({n}).' => '',
);
