<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<b>Внимание:</b> Скидки для администраторов запрещены.' => '',
  'Активен' => '',
  'Все скидки' => '',
  'Выберите производителя' => '',
  'Выберите роли' => '',
  'Группы пользователей' => '',
  'Да' => '',
  'Дата начала' => '',
  'Дата окончания' => '',
  'Здесь вы можете указать категории, для которых будет доступна скидка.' => '',
  'Изменения успешно сохранены' => '',
  'Категории' => '',
  'Название' => '',
  'Нет' => '',
  'Общая информация' => '',
  'Персональная скидка' => '',
  'Поиск:' => '',
  'Производители' => '',
  'Редактирование скидки' => '',
  'Скидка' => '',
  'Скидка не найдена.' => '',
  'Скидки' => '',
  'Создание скидки' => '',
  'Создать скидку' => '',
  'Укажите целое число или процент. Например 10%.' => '',
  'Управление скидками для продуктов.' => '',
);
