<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => '',
  'Ваш номер телефона' => '',
  'Ваш отзыв' => '',
  'Ваше имя' => '',
  'Ваше сообщение отправлено' => '',
  'Длина сообщения' => '',
  'Если у вас появились вопросы или замечания по работе нашего интернет-магазина, свяжитесь с нами через форму обратной связи. <br>
  Мы ответим вам в ближайшее время' => '',
  'Изменения успешно сохранены' => '',
  'Использовать код протекции для защиты от спама.' => '',
  'Код проверки' => '',
  'Код протекции' => '',
  'Модули' => '',
  'Обеспечивает работу формы обратной связи на вашем сайте.' => '',
  'Обратная связь' => '',
  'Отправить' => '',
  'Сообщение от {name}' => '',
  'Сохранить' => '',
  'Спасибо. Ваше сообщение отправлено.' => '',
  'Укажите email куда отправлять новые сообщения.' => '',
  'Укажите максимальную длину сообщения.' => '',
  'Форма заказа обратного звонка' => '',
  'Форма обратной связи' => '',
  'Электронная почта' => '',
);
