<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'id задачи' => '',
  'Внутренний идентификатор задачи' => '',
  'Выполнение' => '',
  'Добавить поток' => '',
  'Завершить поток' => '',
  'Задач в очереде' => '',
  'Когда создана задача' => '',
  'Не удалять после завершения' => '',
  'Обрабатывается' => '',
  'Обработчиков в работе' => '',
  'Обработчиков всего' => '',
  'Ожидание' => '',
  'Перезапустить все потоки' => '',
  'Перезапустить все потоки всех серверов' => '',
  'Потоки на всех серверах перезапущены' => '',
  'Потоки на сервере перезапущены' => '',
  'Потоки по серверам' => '',
  'Псевдоним задачи' => '',
  'Распределенные обработчики задач' => '',
  'Статус задачи' => '',
  'Статус обработчиков задач' => '',
  'Фоновых задач в очереди:' => '',
  'Функция' => '',
  'запущено потоков' => '',
);
