<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action is not instance of IWorkerAction' => '',
  'Call to undefined method "{method}"' => '',
  'Class "{class}" is not found' => '',
  'Class "{class}" is not subclass of CController' => '',
  'Command "{command}" is registered now' => '',
  'Gearman job object not setted to controller action' => '',
  'Invalid controller id' => '',
  'Parameter "$route" must be string, array(2) or IWorkerRoute object, {type} given' => '',
);
