<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '1С бухгалтерия' => '',
  'Директория' => '',
  'Изменения успешно сохранены' => '',
  'Модули' => '',
  'Обмен товарами.' => '',
  'Пароль' => '',
  'Пароль доступа' => '',
  'Поддержка 1С бухгалтерии.' => '',
  'Путь к временной директории для загрузки xml файлов и изображений' => '',
  'Сcылка импорта:' => '',
  'Сохранить' => '',
  'Укажите IP сервера 1C  с которого разрешено принимать подключения' => '',
);
