<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => '',
  'Для завершения установки удалите файл install.php' => '',
  'Имя пользователя' => '',
  'Исправьте ошибки и нажмите <a href="/install.php">Обновить</a>' => '',
  'Логин' => '',
  'Название' => '',
  'Название сайта' => '',
  'Ошибка подключения к БД' => '',
  'Пароль' => '',
  'Посмотреть сайт' => '',
  'Продолжить' => '',
  'Следующий список директорий и файлов должен быть доступен для записи.' => '',
  'Сохранить' => '',
  'Установить' => '',
  'Установить демонстрационные данные' => '',
  'Установка завершена.' => '',
  'Учётная запись администратора' => '',
  'Хост' => '',
  'Шаг 1. Проверка.' => '',
  'Шаг 2. Подключение к БД.' => '',
  'Шаг 3. Настройка.' => '',
);
