<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add…' => '',
  'Close' => '',
  'Description' => '',
  'Drop Files Here…' => '',
  'Edit' => '',
  'Edit information' => '',
  'Name' => '',
  'Remove' => '',
  'Save changes' => '',
  'Select all' => '',
  'Uploading images…' => '',
  'XML' => '',
  'В источнике отсустствует информация о валюте, существующей в магазине:' => '',
  'Валюта, выбранная базовой для конвертации:' => '',
  'Данные' => '',
  'Загружено из кеша' => '',
  'Загрузить файл' => '',
  'Каталог товаров' => '',
  'Количество валют в источнике:' => '',
  'Количество валют магазина:' => '',
  'Найдено категорий:' => '',
  'Найдено производителей:' => '',
  'Найдено товаров:' => '',
  'Найдено характеристик:' => '',
  'Не корректный YML-файл' => '',
  'Не обнаружено соответствие валют.' => '',
  'Невозможно загрузить файл' => '',
  'Новый атрибут' => '',
  'Новый производитель' => '',
  'Отзывы пользователей' => '',
  'Отсутствует информация о валютах!' => '',
  'Отсутствует информация об основной валюте магазина!' => '',
  'Ошибка' => '',
  'Ошибка загрузки файла' => '',
  'Ошибок:' => '',
  'Панель управления' => '',
  'Перейти к сопоставлению данных' => '',
  'Приведенные курсы валют: ' => '',
  'Ссылка' => '',
  'Страница' => '',
  'У вас есть магазин?<br/>Присоединяйтесь!' => '',
  'основная валюта:' => '',
);
