<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Meta Description' => '',
  'Meta Keywords' => '',
  'Meta Title' => '',
  'URL' => '',
  'Автор' => '',
  'Архив' => '',
  'В категории нет страниц.' => '',
  'Внешний вид' => '',
  'Дата обновления' => '',
  'Дата публикации' => '',
  'Дата создания' => '',
  'Дополнительно' => '',
  'Ждет одобрения' => '',
  'Заглавление' => '',
  'Записей на странице' => '',
  'Изменения успешно сохранены' => '',
  'Категории' => '',
  'Категория' => '',
  'Категория не найдена.' => '',
  'Краткое описание' => '',
  'Макет' => '',
  'Мета данные' => '',
  'Название' => '',
  'Нет' => '',
  'Описание' => '',
  'Опубликован' => '',
  'Параметры' => '',
  'Редактирование категории' => '',
  'Редактирование страницы' => '',
  'Родитель' => '',
  'Содержание' => '',
  'Содержимое' => '',
  'Создание категории' => '',
  'Создание страницы' => '',
  'Создать категорию' => '',
  'Создать страницу' => '',
  'Статус' => '',
  'Страница не найдена.' => '',
  'Страницы' => '',
  'Управление страницами сайта.' => '',
  'Черновик' => '',
  'Шаблон' => '',
);
