<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' отсутствует' => '',
  '" в:' => '',
  'Вставить новую строку в исходный язык' => '',
  'Выбранный язык не найден' => '',
  'Действия' => '',
  'Добавить строку' => '',
  'Других языков не найдено, создайте подпапки для других языков в:' => '',
  'Значение' => '',
  'Исходный перевод отсутствует!' => '',
  'Исходный язык:' => '',
  'Ключ' => '',
  'Локализация' => '',
  'Модуль переводов определил следующие настройки (измените конфигурацию, если он не верны):' => '',
  'Найдены следующие языки в папке' => '',
  'Нет отсутствующих файлов' => '',
  'Ошибка формата файла (не массив)' => '',
  'Папка для языка не найдена, создайте папку "' => '',
  'Перевести' => '',
  'Перевод' => '',
  'Поиск' => '',
  'Поиск по переводам' => '',
  'Редактирование перевода:' => '',
  'Редактирование файла перевода:' => '',
  'Редактируемый язык:' => '',
  'Следующие файлы перевода отсутствуют:' => '',
  'Следующие файлы переводов найдены:' => '',
  'Сохранить' => '',
  'Управление локализацией сайта' => '',
  'Файл не найден: ' => '',
  'Файлы переводов в папке' => '',
  'Файлы переводов для выбранного языка не найдены.
        Создайте файл со следующим содержимым:' => '',
  'Язык по-умолчанию:' => '',
  'Языки не найдены, вы должны создать папку "' => '',
  'выбрать другой файл' => '',
  'выбрать другой язык' => '',
  'завершен' => '',
  'на' => '',
  'отсутствует' => '',
  'по переводу:' => '',
);
